apiVersion: apps/v1
kind: Deployment
metadata:
  name: cd-capstone
  labels:
    app: capstone
  namespace: default
spec:
  replicas: 2
  progressDeadlineSeconds: 3600
  selector:
    matchLabels:
      app: capstone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
        - image: nitesh2307/capstone_image1
          imagePullPolicy: Always
          name: hellonitesh
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: cd-capstone
  labels:
    app: capstone
spec:
  type: LoadBalancer
  selector:
    app: capstone
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP